services:
  dockertest:
    image: burningbagel/dockertest
    labels:
      - com.centurylinklabs.watchtower.enable:true
    container_name: dockertest
    ports:
      - 8080:8080 




  watchtower:
    image: nickfedor/watchtower
    environment:
        - WATCHTOWER_POLL_INTERVAL=60
        - WATCHTOWER_LABEL_ENABLE=TRUE
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower 