services:
  dockertest:
    image: burningbagel/dockertest
    container_name: dockertest
    ports:
      - 8080:8080 




  watchtower:
    image: nickfedor/watchtower
    environment:
        - WATCHTOWER_POLL_INTERVAL=20
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    command: dockertest 